export default class Subject {
    codigo_materia: string;
    materia: string;
    tipo: string;
    paralelo: number;
    profesor: string;
    cupo_maximo: number;
    cupo_disponible: number;
    planificada_quincenalmente: string;
    aula_examen_parcial: string;
    aula_examen_final: string;
    aula_mejoramiento: string;
    paralelos_asociados: string;
    dia: string;
    hora_inicio: string;
    hora_fin: string;
    aula: string;
    bloque: string;
    fecha_examen_parcial: string;
    inicio_examen_parcial: string;
    fin_examen_parcial: string;
    fecha_examen_final: string;
    inicio_examen_final: string;
    fin_examen_final: string;
    fecha_examen_mejoramiento: string;
    inicio_examen_mejoramiento: string;
    fin_examen_mejoramiento: string;
    nivel: string;
}
